In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
import pickle

In [2]:
#load the dataset
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1) #axis=1 means drop columns
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [4]:
## encode 'Geography' using one-hot encoding
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder() # drop='first to avoid dummy variable trap
geo_encoded = one_hot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [5]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [6]:
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
#combine one hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# save the encoders and scaler for future use
with open("label_encoder_gender.pkl", "wb") as f:
    pickle.dump(label_encoder_gender,f)

with open("one_hot_encoder_geo.pkl", "wb") as f:
    pickle.dump(one_hot_encoder_geo,f)

In [9]:
#divide the dataset into independent and dependent features
X = data.drop('Exited', axis=1) #independent features
y = data['Exited'] #dependent feature

#split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) #fit_transform is used to fit the scaler on the training data and then transform it
X_test = scaler.transform(X_test) #transform is used to transform the test data using the same scaler fitted on the training data

In [10]:
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler,f)

In [11]:
# define a function to create the model and try different hyperparameters (for KerasClassifier)
def create_model(neurons=32, layers=1):
    model = Sequential()
    model.add(Dense(neurons, activation='relu', input_shape=(X_train.shape[1],)))
    for _ in range(layers - 1):
        model.add(Dense(neurons, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [12]:
#create keras classifier
model = KerasClassifier(neurons=32, layers=1,build_fn=create_model, epochs=50, batch_size=10, verbose=0)

In [13]:
param_grid = {
    'neurons': [16, 32, 64, 128],
    'layers': [1, 2],
    'epochs': [50, 100],
}

In [14]:
#perform grid search
grid= GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train, y_train)

#print best hyperparameters
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:38.862232: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.862274: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.862282: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.862226: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.862467: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.862481: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.862721: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.862721: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.863308: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2026-05-30 17:43:38.863395: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2026-05-30 17:43:38.864492: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.864517: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.864523: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.864548: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.864561: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:38.912853: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.912931: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.912943: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.912994: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.913031: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:38.973700: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.973725: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.973732: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.973755: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.973768: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2026-05-30 17:43:38.976591: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:38.976701: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:38.976720: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:38.976785: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:38.976811: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:39.064301: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:39.064350: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:39.064413: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:39.064459: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:39.064475: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:39.081429: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:39.081467: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:39.081476: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:39.081525: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:39.081544: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:39.120403: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:39.120431: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:39.120436: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:39.120456: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:39.120469: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
2026-05-30 17:43:39.244623: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-30 17:43:39.244653: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-30 17:43:39.244659: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-05-30 17:43:39.244680: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-30 17:43:39.244693: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2026-05-30 17:43:39.946247: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:39.968729: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:39.978008: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.012602: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.037074: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.058116: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.060899: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.091052: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.109174: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-05-30 17:43:40.307776: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/Users/akshitachoudhary/Documents/ann-classification/venv/lib/python3.11/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

KeyboardInterrupt: